config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: 'entries#index'

  resources :entries do
    resources :techniques
  end

  resources :roadmaps
end

app/models/ability.rb
class Ability
  include CanCan::Ability

# NHO: Great job utilizing CanCanCan! How could we make this code my DRY?
  def initialize(user)
    # if user
      can :read, Entry.where({user_id: user})
      can :read, Technique.where({user_id: user})
      can :read, Roadmap.where({user_id: user})
      can :update, Entry.where({user_id: user})
      can :update, Technique.where({user_id: user})
      can :update, Roadmap.where({user_id: user})
    # end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :techniques
  belongs_to :user
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :user
  has_many :techniques
end

app/models/technique.rb
class Technique < ActiveRecord::Base
  belongs_to :entry
  belongs_to :roadmap
  belongs_to :user # NHO: Feel like this relationship would already be established because of the hierarchy of your associations 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries
  has_many :techniques # NHO: Feel like this relationship wouldnt be direct, but rather throguh entries or roadmaps.
  has_many :roadmaps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController <ApplicationController

  def index
    # NHO: convention would be @entries
    @entry =Entry.all # NHO: also something to consider would be how you want these entries ordered...

  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.create!(entry_params.merge(user: current_user))
    redirect_to (entries_path)
  end

  def show
    @entry = Entry.find(params[:id])
    @technique = Technique.all
    authorize! :read, @entry
  end

  def edit
    @entry = Entry.find(params[:id])
    authorize! :update, @entry
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.update(entry_params)
    authorize! :update, @entry
    redirect_to entry_path(@entry)
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_path
  end



  private
  def entry_params
    params.require(:entry).permit(:title, :comments, :sparring_partners)
  end

end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController

  def index
    # NHO: When would you have more than one roadmap?
    @roadmap = Roadmap.all # NHO: @roadmaps
  end

  def show
    @technique = Technique.all # NHO: @techniques
    @user = current_user # NHO: is this instance variable necessary?
    @roadmap = Roadmap.find(params[:id])
    # NHO: would it be more appropriate to have @techniques = @roadmap.techniques?
    authorize! :read, @roadmap
  end

  def new
    @roadmap = Roadmap.new
  end

  def create
    @roadmap = Roadmap.create!(roadmap_params.merge(user: current_user))
    redirect_to roadmaps_path
  end

  def edit
    @roadmap = Roadmap.find(params[:id])
    authorize! :update, @roadmap
  end

  def update
    @roadmap = Roadmap.find(params[:id])
    @roadmap.update(roadmap_params)
    authorize! :update, @roadmap
    redirect_to roadmap_path
  end

  def destroy
    @roadmap = Roadmap.find(params[:id])
    @roadmap.destroy
    redirect_to roadmaps_path
  end


  private
  def roadmap_params
    params.require(:roadmap).permit(:category)
  end






end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController

  def index
    @technique = Technique.all #NHO: @techniques
  end

  def new
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.new
    @roadmap = Roadmap.where({user_id: current_user.id}) # NHO: Roadmap.find, would return 1, Roadmap.where returns an array
  end

  def create
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.create!(technique_params.merge(user: current_user, entry: @entry))
    redirect_to (entry_path(params[:entry_id])) # NHO: shorthand would be redirect_to @entry
  end

  def show
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.find(params[:id])
    authorize! :read, @technique
  end

  def edit
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.find(params[:id])
    @roadmap = Roadmap.where({user_id: current_user.id}) # NHO: Roadmap.find
    authorize! :update, @technique
  end

  def update
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.find(params[:id])
    @technique.update(technique_params.merge(user: current_user))
    authorize! :update, @technique
    redirect_to entry_technique_path(params[:entry_id], params[:id])  # NHO: shorthand would be redirect_to entry_technique_path(@entry, @technique)
  end

  def destroy
    @entry = Entry.find(params[:entry_id])
    @technique = Technique.find(params[:id])
    @technique.destroy
    redirect_to entry_path(@entry)
  end

  # t.integer  "entry_id"
  # t.integer  "user_id"

  private
  def technique_params
    params.require(:technique).permit(:name, :description, :video_url, :roadmap_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# NHO: First helper method I have seen from a student, excellent use here!
  def embed(video_url)
    youtube_id = video_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>

<p>
  <%= f.label :title, :class => 'form_text'%>
  <%= f.text_field :title, :class => 'comments' %>
</p>
<p>
  <%= f.label :comments, :class => 'form_text' %>
  <%= f.text_area :comments, :class => 'comments' %>
</p>
<!-- This is labeled as Comments here in the form, but changes to "Commends and feelings" when viewing your entry -->
<p>
  <%= f.label :sparring_partners, :class => 'form_text' %>
  <%= f.text_field :sparring_partners, :class => 'comments'  %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/entries/edit.html.erb
<h2>Edit Entry</h2>

<%= render 'form' %>

<%= link_to 'Delete!', entry_path(@entry), method: :delete, class: 'delete' %>

app/views/entries/index.html.erb
  <div class="row">
    <div class="col-md-8">
      <div class="well items">
        <h3>Entries</h3>
            <% @entry.each do |entry| %>
              <% if can? :read, entry %>
                <p><%=entry.created_at.strftime("%B %d, %Y")%> : <%= link_to entry.title, entry_path(entry) %></p>
              <% end %>
          <% end %>
      </div>
    </div>
    <div class="col-md-4 entry_new_button">
      <div class="well items">
        <h3>New Entry</h3>
        <p><%= link_to 'New', new_entry_path, :class => "btn btn-success"%></p>
      </div>
    </div>
  </div>

app/views/entries/new.html.erb
<h2>New Entry </h2>

<%= render 'form' %>

app/views/entries/show.html.erb
<!-- NHO: Very clean layout, nice!  -->
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <h2><%= @entry.title %> : <%= @entry.created_at.strftime("%B %d, %Y") %></p></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="well items">
      <h3>Comments and feelings</h3>
      <p><%= @entry.comments %></p>
      <%= link_to 'Edit Entry', edit_entry_path, :class => "btn btn-success" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="well items">
      <h3>Techniques</h3>
        <% @technique.each do |technique| %>
          <% if can? :read, technique %>
            <% if technique.entry_id == @entry.id %>
              <p><%= link_to technique.name, entry_technique_path(@entry, technique) %></p>
            <% end %>
          <% end %>
        <% end %>
        <p><%= link_to 'Add a Technique', new_entry_technique_path(@entry), :class => "btn btn-success"%></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jiujitsu Journal</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Shadows+Into+Light' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:600italic' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <!-- <div class="user-info"> -->
              <% if current_user %>
                <li role="presentation"><%= link_to current_user.email, root_path %></li>
                <li role="presentation"><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li role="presentation"><%= link_to 'Signup', new_user_registration_path %></li>
                <li role="presentation"><%= link_to 'Login', new_user_session_path %></li>
              <% end %>
            <!-- </div> -->
            <!-- <li role="presentation" class="active"><a href="#">Main</a></li>
            <li role="presentation"><a href="#">Sign In</a></li> -->
          </ul>
        </nav>
        <h3 class="text-muted"><%= link_to 'JiuJitsuJournal', entries_path%></h3>
      </div>

      <div class="jumbotron">
        <h1>Jiujitsu Journal</h1>
        <ul class="nav jumbo">
          <li class="li"><%= link_to 'Entry Home', entries_path%></li>
          <li class="li"><%= link_to 'Roadmap', roadmaps_path%></li>
        </ul>
      </div>

      <%= yield %>

      <footer class="footer">
        <p>Project 2 - EJS</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>


  <!-- <h1> Jiujitsu Journal </h1>
  <%= link_to 'Entry Home', entries_path %>

  <nav>
    <div class="user-info">
      <% if current_user %>
        Welcome, <%= current_user.email %>
        <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



 -->

app/views/roadmaps/_form.html.erb
<%= form_for @roadmap do |f| %>

<p>
  <%= f.label :category %>
  <%= f.text_field :category, :class => 'comments'%>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/roadmaps/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <h2>Edit Category Below</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="well items">
        <%= render 'form' %>
    </div>
  </div>
  <div class="col-md-4 roadmap_edit">
    <div class="well items">
      <h3>Delete Category</h3>
      <p><%= link_to 'Delete!', roadmap_path(@roadmap), method: :delete, class: 'delete btn-danger' %></p>
    </div>
  </div>
</div>

app/views/roadmaps/index.html.erb
<div class="row roadmap_top">
  <div class="col-md-12">
    <div class="well items">
      <h2>Jiujitsu Roadmap Categories</h2>
      <p><%= link_to 'Add Category', new_roadmap_path, :class => "btn btn-success"%></p>
    </div>
  </div>
</div>

<div class="row roadmap_body">
    <% @roadmap.each do |roadmap| %>
      <% if can? :read, roadmap %>
        <div class="col-md-3">
          <div class="well items">
            <%= link_to roadmap.category, roadmap_path(roadmap) %>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/roadmaps/new.html.erb
<h2>new tech</h2>

<%= render 'form' %>

app/views/roadmaps/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <h2><%= @roadmap.category %></p></h2>
    </div>
  </div>
</div>

<!-- NHO: Feeling like this code is repeated on the entry show, how could we abstract that out to a shared partial? -->
<div class="row">
  <div class="col-md-8">
    <div class="well items">
      <h3>Techniques</h3>
        <% @technique.each do |technique| %>
          <% if can? :read, technique %>
            <% if technique.roadmap_id == @roadmap.id %>
              <p><%= link_to technique.name, entry_technique_path(technique.entry_id, technique) %></p>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>
  <div class="col-md-4 roadmap_edit">
    <div class="well items">
      <h3>Edit Category</h3>
      <p><%= link_to 'Edit Category', edit_roadmap_path, :class => "btn btn-success" %></p>
    </div>
  </div>
</div>

app/views/techniques/_form.html.erb
<%= form_for ([@entry, @technique]) do |f| %>
<p>
  <%= f.label :name, :class => 'form_text' %>
  <%= f.text_field :name, :class => 'comments'  %>
</p>
<p>
  <%= f.label :description, :class => 'form_text' %>
  <%= f.text_area :description, :class => 'comments'  %>
</p>
<p>
  <%= f.label :video_url, :class => 'form_text'%>
  <%= f.text_field :video_url, :class => 'comments' %>
</p>
<!-- NHO: Great use of a collection_select!  -->
<p>
  <%= f.label :roadmap_id %>
  <%= f.collection_select :roadmap_id, @roadmap, :id, :category%>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/techniques/edit.html.erb
<h2>Edit Techniques</h2>

<%= render 'form' %>

<%= link_to 'Delete!', entry_technique_path(@entry, @technique), method: :delete, class: 'delete btn-danger' %>

app/views/techniques/new.html.erb
<h2> New Techniques </h2>

<%= render 'form' %>

app/views/techniques/show.html.erb
<div class ="row">
  <h2><%= @technique.name %></h2>
  <div class="col-md-12">
    <div class="embed-container">
      <%= embed(@technique.video_url) %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="well items">
      <h3>Technique Description</h3>
      <p><%= @technique.description %></p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="well items">
      <%= link_to 'Edit Technique', edit_entry_technique_path(@entry, @technique), :class => "btn btn-success" %>
    </div>
  </div>
</div>